import "./src/styles/dhc-tokens.css";
import "./src/styles/global.css";
import "./src/styles/layout.css";
import React from "react";
import { Amplify } from "aws-amplify";
import outputs from "./src/amplify_outputs.json";
import { AuthProvider } from "./src/context/AuthContext";
import { SmartHomeProvider } from "./src/context/SmartHomeContext";

// Amplify Gen 2: a single amplify_outputs.json holds Cognito User Pool,
// AppSync API, S3 bucket, and Identity Pool config. Generated by
// `npx ampx sandbox` (dev) or `npx ampx pipeline-deploy` (CI).
Amplify.configure(outputs);

export const wrapRootElement = ({ element }) => (
  <AuthProvider>
    <SmartHomeProvider>{element}</SmartHomeProvider>
  </AuthProvider>
);
