import "./src/styles/global.css";
import React from "react";
import { Amplify } from "aws-amplify";
import awsExports from "./src/aws-exports.deployment";
import { AuthProvider } from "./src/context/AuthContext";

// Configure Amplify with the backend config generated by `amplify pull`
Amplify.configure(awsExports);

export const wrapRootElement = ({ element }) => (
  <AuthProvider>{element}</AuthProvider>
);
