// Example stub for aws-exports.js
// This file is NOT used at runtime. The real src/aws-exports.js
// is generated by `amplify pull` in the Amplify build pipeline
// and should not be committed to Git.
//
// In your own setup, run:
//   amplify pull --appId <your-backend-app-id> --envName <env> --yes
//
// and Amplify will create a proper src/aws-exports.js next to this file.

const awsmobile = {
  aws_project_region: "eu-central-1",
  // ... other fields injected by Amplify
};

export default awsmobile;
